spring:
  security:
    user:
      name: user
      password: password #PasswordEncoder.encode(password)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring_order # Docker 밖에서 실행할 때
    # url: jdbc:mariadb://host.docker.internal:3306/spring_order # Docker를 실행할 때
    username: root
    password: 1234
  jpa:
    databases: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  expiration: 30 #30분
  secretKey: mysecret
